const missions=[['pelicano','Florida','🦅','Encontrar un pelícano en la playa',5,'playa'],['dulce','Florida','🍬','Probar un dulce nuevo',5,'dulces'],['caballo','Florida','🐴','Ver un caballo de cerca o montarlo',10,'caballos'],['pez','Caribe','🐠','Ver un pez tropical de colores',10,'playa'],['foto','Florida','📸','Tomarse una foto familiar perfecta',5,'foto'],['atraccion','Busch Gardens','🎢','Montar la atracción más emocionante',15,'valiente'],['atardecer','Florida','🌅','Ver un amanecer o atardecer',10,'playa'],['castillo','Florida','🏰','Construir un castillo de arena',10,'playa'],['conchas','Florida','🐚','Encontrar 3 conchas bonitas',5,'playa'],['olas','Caribe','🌊','Saltar 5 olas seguidas',5,'playa'],['cangrejo','Florida','🦀','Ver un cangrejo corriendo',10,'animales'],['crucero','Crucero','🛳️','Explorar el crucero de popa a proa',10,'capitan'],['animal','Busch Gardens','🦁','Ver un animal salvaje grande',10,'animales'],['palmera','Florida','🌴','Encontrar una palmera gigante',5,'playa'],['snorkel','Caribe','🤿','Hacer snorkel o ver peces',15,'playa'],['ingles','Florida','⭐','Hablar con alguien en inglés',10,'valiente'],['pizza','Florida','🍕','Comer pizza americana gigante',5,'dulces'],['musica','Crucero','🎵','Escuchar música en vivo o bailar',10,'capitan'],['pajaros','Florida','🐦','Identificar 3 pájaros diferentes',10,'animales'],['secreta','Caribe','🌺','Misión secreta inventada por Juan',20,'aventura']].map(x=>({id:x[0],place:x[1],icon:x[2],title:x[3],pts:x[4],badge:x[5]}));
const badgeMap={animales:['🦁','Amigo de animales'],playa:['🌊','Rey de la playa'],capitan:['⚓','Capitán del crucero'],valiente:['🎢','Valiente'],dulces:['🍬','Catador de dulces'],caballos:['🐴','Amigo de caballos'],foto:['📸','Fotógrafo'],aventura:['🧭','Explorador']};
let state=JSON.parse(localStorage.getItem('jmAdventure')||'{"done":{},"notes":{},"diary":"","worldcup":{}}');
const save=()=>localStorage.setItem('jmAdventure',JSON.stringify(state));
function rank(score){if(score>=195)return '🏆 Explorador Supremo'; if(score>=150)return '⭐⭐⭐ Explorador Élite'; if(score>=100)return '⭐⭐ Gran Explorador'; return '⭐ Explorador Junior'}
function render(){
 const score=missions.filter(m=>state.done[m.id]).reduce((a,m)=>a+m.pts,0),total=missions.reduce((a,m)=>a+m.pts,0),doneCount=missions.filter(m=>state.done[m.id]).length;
 xpBar.style.width=Math.min(100,score/total*100)+'%';xpText.textContent=`${score} / ${total} puntos`;level.textContent=Math.max(1,Math.floor(score/40)+1);rankText.textContent=rank(score);scoreBig.textContent=score;doneBig.textContent=doneCount;
 const unlocked=new Set(missions.filter(m=>state.done[m.id]).map(m=>m.badge));badgeBig.textContent=unlocked.size;
 progressList.innerHTML=['Florida','Crucero','Busch Gardens','Caribe'].map(p=>{const all=missions.filter(m=>m.place===p),done=all.filter(m=>state.done[m.id]).length,pct=Math.round(done/all.length*100);return `<div class="place"><b>${p}</b><div class="bar"><span style="width:${pct}%"></span></div><b>${pct}%</b></div>`}).join('');
 badges.innerHTML=Object.entries(badgeMap).map(([k,v])=>`<div class="badge-card ${unlocked.has(k)?'on':''}"><div class="icon">${v[0]}</div>${v[1]}</div>`).join('');
 document.getElementById('missions').innerHTML=missions.map(m=>`<div class="mission ${state.done[m.id]?'done':''}"><h3>${m.icon} ${m.title}</h3><p><b>${m.place}</b> · ${m.pts} puntos</p><label><input type="checkbox" ${state.done[m.id]?'checked':''} onchange="toggleMission('${m.id}',this.checked)"> ¡Lo logré!</label><textarea placeholder="Escribe o dicta qué pasó..." oninput="saveNote('${m.id}',this.value)">${state.notes[m.id]||''}</textarea></div>`).join('');
 diplomaText.textContent=score>=total?'🏆 ¡Explorador Supremo desbloqueado!':`Te faltan ${total-score} puntos para completar la aventura.`;diary.value=state.diary||'';wc1.value=state.worldcup.wc1||'';wc2.value=state.worldcup.wc2||'';wc3.value=state.worldcup.wc3||'';
}
function toggleMission(id,checked){state.done[id]=checked;save();render();if(checked)showToast('🎉 ¡Misión cumplida! El progreso subió')}
function saveNote(id,value){state.notes[id]=value;save()}function showToast(msg){toast.textContent=msg;toast.style.display='block';setTimeout(()=>toast.style.display='none',2200)}
saveDiary.onclick=()=>{state.diary=diary.value;save();showToast('📘 Diario guardado')};
saveWorldcup.onclick=()=>{state.worldcup={wc1:wc1.value,wc2:wc2.value,wc3:wc3.value};save();showToast('⚽ Mundial guardado')};
resetBtn.onclick=()=>{if(confirm('¿Reiniciar toda la aventura?')){localStorage.removeItem('jmAdventure');state={done:{},notes:{},diary:'',worldcup:{}};render()}};
render();
