const missions=[['pelicano','Florida','🦅','Encontrar un pelícano en la playa',50,'playa'],['dulce','Florida','🍬','Probar un dulce nuevo',50,'dulces'],['caballo','Florida','🐴','Ver un caballo de cerca o montarlo',100,'caballos'],['pez','Caribe','🐠','Ver un pez tropical de colores',100,'playa'],['foto','Florida','📸','Tomarse una foto familiar perfecta',50,'foto'],['atraccion','Busch Gardens','🎢','Montar la atracción más emocionante',150,'valiente'],['atardecer','Florida','🌅','Ver un amanecer o atardecer',100,'playa'],['castillo','Florida','🏰','Construir un castillo de arena',100,'playa'],['conchas','Florida','🐚','Encontrar 3 conchas bonitas',50,'playa'],['olas','Caribe','🌊','Saltar 5 olas seguidas',50,'playa'],['cangrejo','Florida','🦀','Ver un cangrejo corriendo',100,'animales'],['crucero','Crucero','🛳️','Explorar el crucero de popa a proa',100,'capitan'],['animal','Busch Gardens','🦁','Ver un animal salvaje grande',100,'animales'],['palmera','Florida','🌴','Encontrar una palmera gigante',50,'playa'],['snorkel','Caribe','🤿','Hacer snorkel o ver peces',150,'playa'],['ingles','Florida','⭐','Hablar con alguien en inglés',100,'valiente'],['pizza','Florida','🍕','Comer pizza americana gigante',50,'dulces'],['musica','Crucero','🎵','Escuchar música en vivo o bailar',100,'capitan'],['pajaros','Florida','🐦','Identificar 3 pájaros diferentes',100,'animales'],['secreta','Caribe','🌺','Misión secreta inventada por Juan',200,'aventura']].map(x=>({id:x[0],place:x[1],icon:x[2],title:x[3],xp:x[4],badge:x[5]}));
const badgeMap={animales:['🦁','Amigo de animales'],playa:['🌊','Rey de la playa'],capitan:['⚓','Capitán del crucero'],valiente:['🎢','Valiente'],dulces:['🍬','Catador de dulces'],caballos:['🐴','Amigo de caballos'],foto:['📸','Fotógrafo'],aventura:['🧭','Explorador']};
let state=JSON.parse(localStorage.getItem('jmAdventure')||'{"done":{},"notes":{},"diary":""}');
const save=()=>localStorage.setItem('jmAdventure',JSON.stringify(state));
function render(){const xp=missions.filter(m=>state.done[m.id]).reduce((a,m)=>a+m.xp,0),total=missions.reduce((a,m)=>a+m.xp,0);xpBar.style.width=Math.min(100,xp/600*100)+'%';xpText.textContent=`${xp} / 600 XP`;level.textContent=Math.max(1,Math.floor(xp/200)+1);
progressList.innerHTML=['Florida','Crucero','Busch Gardens','Caribe'].map(p=>{const all=missions.filter(m=>m.place===p),done=all.filter(m=>state.done[m.id]).length,pct=Math.round(done/all.length*100);return `<div class="place"><b>${p}</b><div class="bar"><span style="width:${pct}%"></span></div><b>${pct}%</b></div>`}).join('');
const unlocked=new Set(missions.filter(m=>state.done[m.id]).map(m=>m.badge));badges.innerHTML=Object.entries(badgeMap).map(([k,v])=>`<div class="badge-card ${unlocked.has(k)?'on':''}"><div class="icon">${v[0]}</div>${v[1]}</div>`).join('');
document.getElementById('missions').innerHTML=missions.map(m=>`<div class="mission ${state.done[m.id]?'done':''}"><h3>${m.icon} ${m.title}</h3><p><b>${m.place}</b> · +${m.xp} XP</p><label><input type="checkbox" ${state.done[m.id]?'checked':''} onchange="toggleMission('${m.id}',this.checked)"> ¡Lo logré!</label><textarea placeholder="Escribe o dicta qué pasó..." oninput="saveNote('${m.id}',this.value)">${state.notes[m.id]||''}</textarea></div>`).join('');
diplomaText.textContent=xp>=total?'🏆 ¡Explorador Supremo desbloqueado!':`Te faltan ${total-xp} XP para completar la aventura.`;diary.value=state.diary||''}
function toggleMission(id,checked){state.done[id]=checked;save();render();if(checked)showToast('🎉 ¡Misión cumplida! Ganaste una insignia')}
function saveNote(id,value){state.notes[id]=value;save()}function showToast(msg){toast.textContent=msg;toast.style.display='block';setTimeout(()=>toast.style.display='none',2200)}
saveDiary.onclick=()=>{state.diary=diary.value;save();showToast('📘 Diario guardado')};resetBtn.onclick=()=>{if(confirm('¿Reiniciar toda la aventura?')){localStorage.removeItem('jmAdventure');state={done:{},notes:{},diary:''};render()}};render();
